backend/controllers/MoviesController.php
<?php

class MoviesController extends EGxController
{


    public $layout = '//layouts/column2';

    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Movies'),
        ));
    }

    public function actionCreate()
    {
        $model = new Movies;


        if (isset($_POST['Movies'])) {
            $model->setAttributes($_POST['Movies']);

            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        $model = $this->loadModel($id, 'Movies');


        if (isset($_POST['Movies'])) {
            $model->setAttributes($_POST['Movies']);

            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id)
    {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $this->loadModel($id, 'Movies')->delete();

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Movies');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionAdmin()
    {
        $model = new Movies('search');
        $model->unsetAttributes();

        if (isset($_GET['Movies']))
            $model->setAttributes($_GET['Movies']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }


    public function actionRescan123OldVersionTest()
    {

        foreach ($playlistListFeed as $playlistEntry) {


            $videoFeed = $yt->getPlaylistVideoFeed($playlistEntry->getPlaylistVideoFeedUrl());
            $i = 1;

            echo '<br/><br/><strong>' . $movie->id . ') ' . $videoFeed->getTitle() . "</strong><br/>";

            /**
             * @var Zend_Gdata_YouTube_VideoEntry $videoEntry
             */

            foreach ($videoFeed as $videoEntry) {
                $q = new CDbCriteria();
                $q->addSearchCondition('youtube_url', substr($videoEntry->getFlashPlayerUrl(), 26, 11));
                $video = Videos::model()->find($q);
                if (is_null($video)) $video = new Videos();

                echo '<br/>';
                if ($video->isNewRecord) echo ' ' . $video->sorder = $i++;
                echo ' ' . $video->name = trim(str_replace(array('Мир Приключений - ', 'Мир приключений - '), '', $videoEntry->getTitle()));
                echo ' ' . CHtml::link('ссылка', $video->youtube_url = $videoEntry->getVideoWatchPageUrl());
                echo ' ' . $video->end = $videoEntry->getVideoDuration() - 24;
                $video->movie_id = $movie->id;
                if (!$error = $video->save(false)) {
                    echo "<br/>ОШИБКА ЗАПИСИ!<br/>";
                }

            }
            //	echo $playlistEntry->title->text . "\n";
            //	echo $playlistEntry->description->text . "\n";
        }
    }


    public function actionRescan123()
    {
        Yii::import('vendor.*');

        require_once 'google/apiclient/src/Google/Client.php';
        require_once 'google/apiclient/src/Google/Service/YouTube.php';
        require_once 'google/apiclient/src/Google/Auth/AssertionCredentials.php';

        $key = file_get_contents(Yii::getPathOfAlias('application').'/../API Project-787997783c90.p12');

        $client = new Google_Client();
        $client->setApplicationName("Mir");
        $assertionCredentials = new Google_Auth_AssertionCredentials(
            '364605236788-jol0qhebs1o8keh5fbp6odthvjs3cutl@developer.gserviceaccount.com',[
            'https://www.googleapis.com/auth/youtube',
            'https://www.googleapis.com/auth/youtube.readonly'
        ], $key, 'notasecret');
        $client->setAssertionCredentials($assertionCredentials);
        $client->setClientId('364605236788-jol0qhebs1o8keh5fbp6odthvjs3cutl.apps.googleusercontent.com');

        $youtube = new Google_Service_YouTube($client);

        $playlists = $youtube->playlists->listPlaylists('id, snippet', [
            'channelId' => 'UCKMeh2DHG8TTEdvCozVUvww',
            'maxResults' => 50,
        ]);

        try {
            $v = $p = 0;
            foreach ($playlists->getItems() as $playlistItem) {
                $p++;
                $movie = Movies::model()->findByAttributes([
                    'playlist_id' => $playlistItem->getId()
                ]);
                if (!$movie) continue;

                $playlistItemsResponse = $youtube->playlistItems->listPlaylistItems('snippet', array(
                    'playlistId' => $playlistItem->getId(),
                    'maxResults' => 50
                ));
                echo '<br/><br/><strong>' . $movie->id . ') ' . $playlistItem->getSnippet()->title . "</strong><br/>";

                $i = $k = 1;
                foreach ($playlistItemsResponse->getItems() as $video) {
                    $v++;
                    $q = new CDbCriteria();
                    $q->addSearchCondition('youtube_url', $video['snippet']['resourceId']['videoId']);
                    $videoModel = Videos::model()->find($q);
                    if (is_null($videoModel)) $videoModel = new Videos();

                    echo '<br/>';
                    if ($videoModel->isNewRecord) echo '*' . $videoModel->sorder = $i++;
                    else echo ' '.$k++;
                    echo ' ' . $videoModel->name = trim(str_replace(array('Мир Приключений - ', 'Мир приключений - '), '', $video['snippet']['title']));
                    echo ' ' . CHtml::link('ссылка', $videoModel->youtube_url = sprintf('https://www.youtube.com/watch?v=%s&feature=youtube_gdata_player', $video['snippet']['resourceId']['videoId']));
                //    echo ' ' . $videoModel->end = '----';//$video->getVideoDuration() - 24;
                    $videoModel->movie_id = $movie->id;

                    if (!$error = $videoModel->save(false)) {
                        echo "<br/>ОШИБКА ЗАПИСИ!<br/>";
                    }

                }
            }
            echo '<br/>';
            echo '<hr/>';
            echo 'Total found: playlists '.$p.', videos '.$v;

        } catch (Google_Service_Exception $e) {
            echo sprintf('<p>A service error occurred: <code>%s</code></p>',
                htmlspecialchars($e->getMessage()));
        } catch (Google_Exception $e) {
            echo sprintf('<p>An client error occurred: <code>%s</code></p>',
                htmlspecialchars($e->getMessage()));
        }
    }
}

backend/controllers/TripsController.php
<?php

class TripsController extends EGxController {


    public $layout='//layouts/column2';

    public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Trips'),
		));
	}

	public function actionCreate() {
		$model = new Trips;


		if (isset($_POST['Trips'])) {
			$model->setAttributes($_POST['Trips']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Trips');


		if (isset($_POST['Trips'])) {
			$model->setAttributes($_POST['Trips']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Trips')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Trips');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Trips('search');
		$model->unsetAttributes();

		if (isset($_GET['Trips']))
			$model->setAttributes($_GET['Trips']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

frontend/controllers/MoviesController.php
<?php

class MoviesController extends EGxController {

    public $layout='//layouts/column2';
    private $lang;
	private $otherLang;
	private $entity;
	
	function __construct($id, $module) {
		foreach (['film','movie','saint'] as $entity) {
			if (strpos(Yii::app()->request->requestUri,$entity) !== false) $this->entity = $entity;
		}
		if (!$this->entity) die('wrong entity');

		parent::__construct($id, $module);
	}

	public function actionView($id) {
		$this->lang = Yii::app()->getLanguage(); $this->otherLang = str_replace($this->lang,'','enru');
		$this->render($this->entity, array(
			'model' => $this->loadModel($id, 'Movies',[
                'select' => "id, active, sorder, dates, url,
                    length, quality, weight, days_spent,
                    COALESCE(title_$this->lang, title_$this->otherLang) as title, COALESCE(description_$this->lang, description_$this->otherLang) as description"
            ])
		));
	}

	public function actionIndex() {
		$this->lang = Yii::app()->getLanguage(); $this->otherLang = str_replace($this->lang,'','enru');
		$criteria = new CDbCriteria;

		$criteria->with = array(($this->entity == 'film')?'videos':'videos2');
		$criteria->together = true;

		$criteria->condition = 'active=1'.(($this->entity == 'film')?' AND url!=""':'').($this->entity == 'saint'?" AND series='saint'":' AND series IS NULL');

		$criteria->order = '`t`.`sorder` DESC';


		$criteria->select = ['id', 'active', 'sorder', 'dates', 'url',
			'length', 'quality', 'weight', 'days_spent',
			"COALESCE(title_$this->lang, title_$this->otherLang) as title",
			"COALESCE(description_$this->lang, description_$this->otherLang) as description"];


        $dataProvider = new CActiveDataProvider('Movies', array(
            'pagination'=>array(
				'pageSize'=>30,
			),

			'criteria'=>$criteria,
			'countCriteria'=>array(
				'condition'=> $criteria->condition
			),

			)
		);
		//die($this->lang);
		$this->render($this->entity.'s', array(
			'dataProvider' => $dataProvider,
		));
	}

	// Movies videos || Films by Country
    public function actionCountry($id) {
		$this->lang = Yii::app()->getLanguage(); $this->otherLang = str_replace($this->lang,'','enru');
		$criteria = new CDbCriteria;

	    $criteria->with = array('moviesCountries');

		$criteria->condition = 'active=1'.(($this->entity == 'film')?' AND url!=""':'').($this->entity == 'saint'?" AND series='saint'":' AND series IS NULL');

		$criteria->order = 'sorder DESC';

	    $criteria->together = true;
	    $criteria->compare('moviesCountries.country_id', $id);
		$criteria->select = ['id', 'active', 'sorder', 'dates', 'url',
			'length', 'quality', 'weight', 'days_spent',
			"COALESCE(title_$this->lang, title_$this->otherLang) as title",
			"COALESCE(description_$this->lang, description_$this->otherLang) as description"];

        $dataProvider=new CActiveDataProvider('Movies', array(
            'criteria'=>$criteria,
            'countCriteria'=>$criteria,
           /* array(
	            'condition'=>'active=1',
	         // 'order' and 'with' clauses have no meaning for the count query
            ),
*/ 			'pagination'=>array(
                'pageSize'=>30,
            ),
        ));

		$this->render($this->entity.'s', array(
			'dataProvider' => $dataProvider,
			'selectedCountryId'=> $id,
		));
	}


}

backend/views/movies/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'movies-form',
	'enableAjaxValidation' => false,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'active'); ?>
		<?php echo $form->checkBox($model, 'active'); ?>
		<?php echo $form->error($model,'active'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'sorder'); ?>
		<?php echo $form->textField($model, 'sorder'); ?>
		<?php echo $form->error($model,'sorder'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model, 'title', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'title'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model, 'description'); ?>
		<?php echo $form->error($model,'description'); ?>
		</div><!-- row -->
		<div class="row">

		<?php echo $form->labelEx($model,'forum_url'); ?>
		<?php echo $form->textField($model, 'forum_url', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'forum_url'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'dates'); ?>
		<?php echo $form->textField($model, 'dates', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'dates'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'length'); ?>
		<?php echo $form->textField($model, 'length', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'length'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'quality'); ?>
		<?php echo $form->textField($model, 'quality', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'quality'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'weight'); ?>
		<?php echo $form->textField($model, 'weight', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'weight'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'playlist_id'); ?>
		<?php echo $form->textField($model, 'playlist_id', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'playlist_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'days_spent'); ?>
		<?php echo $form->textField($model, 'days_spent'); ?>
		<?php echo $form->error($model,'days_spent'); ?>
		</div><!-- row -->

		<label><?php echo GxHtml::encode($model->getRelationLabel('trips')); ?></label>
		<?php echo $form->checkBoxList($model, 'trips', GxHtml::encodeEx(GxHtml::listDataEx(Trips::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('videos')); ?></label>
		<?php echo $form->checkBoxList($model, 'videos', GxHtml::encodeEx(GxHtml::listDataEx(Videos::model()->findAllAttributes(null, true)), false, true)); ?>

<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

backend/views/movies/_frontend_view.php
<!--/**
 * MANY_MANY  Ajax Crud Administration
 *  _frontend_view.php   partial view for rendering  movies *    records  in ListView,in frontend views.
 * InfoWebSphere {@link http://libkal.gr/infowebsphere}
 * @author  Spiros Kabasakalis <kabasakalis@gmail.com>
 * @link http://reverbnation.com/spiroskabasakalis/
 * @copyright Copyright &copy; 2011-2012 Spiros Kabasakalis
 * @since 1.0
 * @ver 1.0
 * @license The MIT License
 */-->

<?php 
/**If you want you can use $img_url in thumb source url,so that you can fall back to a placeholder image,if no image exists for model.*/

$thumb_src=$data->moviesImgBehavior->getFileUrl('thumb');
$img_url=(isset($thumb_src))?$thumb_src:
Yii::app()->baseUrl.'/img/placeholder_100.jpg';

?>
<div class="list_partial_view">

    <?php echo GxHtml::encode($data->getAttributeLabel('id    ')); ?>:
    <?php echo GxHtml::encode($data->id)?>
    <br/>

    <div class="thumb_wrapper" id="tmb_wrapper_<?php echo $data->id;?>">
        <img id="<?php echo 'thumb_' . $data->id;?>"
             src="<?php  echo $img_url;?>?<?php echo time();?>"
             title="<?php echo $data->id;?>"/>
    </div>
    <div class='info'
    '>
    <div class='clear'>
        <?php echo GxHtml::encode($data->getAttributeLabel('title')); ?>:
                <?php echo GxHtml::encode($data->title); ?>
                <br/>
                <?php echo GxHtml::encode($data->getAttributeLabel('description')); ?>:
                <?php echo GxHtml::encode($data->description); ?>
                <br/>
            </div>
    <div class="crud_buttons">
        <a id="view_<?php echo $data->id;?>"
           class="movies_properties"
           rel="<?php echo $data->name;?>" href="#">
            <img src="<?php  echo Yii::app()->baseUrl;?>/js_plugins/ajaxform/images/icons/properties.png"
                 alt="View"/>
        </a>
    </div>
</div>
</div>

backend/views/movies/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'id'); ?>
		<?php echo $form->textField($model, 'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'active'); ?>
		<?php echo $form->dropDownList($model, 'active', array('0' => Yii::t('app', 'No'), '1' => Yii::t('app', 'Yes')), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'sorder'); ?>
		<?php echo $form->textField($model, 'sorder'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'title'); ?>
		<?php echo $form->textField($model, 'title', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'description'); ?>
		<?php echo $form->textArea($model, 'description'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'thumbnail'); ?>
		<?php echo $form->textField($model, 'thumbnail', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'forum_url'); ?>
		<?php echo $form->textField($model, 'forum_url', array('maxlength' => 255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'dates'); ?>
		<?php echo $form->textField($model, 'dates', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'length'); ?>
		<?php echo $form->textField($model, 'length', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'quality'); ?>
		<?php echo $form->textField($model, 'quality', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'weight'); ?>
		<?php echo $form->textField($model, 'weight', array('maxlength' => 45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'playlist_id'); ?>
		<?php echo $form->textField($model, 'playlist_id', array('maxlength' => 255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'days_spent'); ?>
		<?php echo $form->textField($model, 'days_spent'); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

backend/views/movies/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('active')); ?>:
	<?php echo GxHtml::encode($data->active); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('sorder')); ?>:
	<?php echo GxHtml::encode($data->sorder); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('title')); ?>:
	<?php echo GxHtml::encode($data->title); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('description')); ?>:
	<?php echo GxHtml::encode($data->description); ?>
	<br />

	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('dates')); ?>:
	<?php echo GxHtml::encode($data->dates); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('length')); ?>:
	<?php echo GxHtml::encode($data->length); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('quality')); ?>:
	<?php echo GxHtml::encode($data->quality); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('weight')); ?>:
	<?php echo GxHtml::encode($data->weight); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('playlist_id')); ?>:
	<?php echo GxHtml::encode($data->playlist_id); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('days_spent')); ?>:
	<?php echo GxHtml::encode($data->days_spent); ?>
	<br />
	*/ ?>

</div>

backend/views/movies/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('movies-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>


<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'movies-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'id',
		array(
					'name' => 'active',
					'value' => '($data->active === 0) ? Yii::t(\'app\', \'No\') : Yii::t(\'app\', \'Yes\')',
					'filter' => array('0' => Yii::t('app', 'No'), '1' => Yii::t('app', 'Yes')),
					),
		'sorder',
		'title',
		'description',
		'thumbnail',
		/*
		'forum_url',
		'dates',
		'length',
		'quality',
		'weight',
		'playlist_id',
		'days_spent',
		*/
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

backend/views/movies/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

backend/views/movies/index.php
<?php

$this->breadcrumbs = array(
	Movies::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . Movies::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . Movies::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Movies::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

backend/views/movies/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(
	array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

backend/views/movies/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
        'id',
        'active:boolean',
        'sorder',
        'title',
        'description',
        'thumbnail',
        'forum_url',
        'dates',
        'length',
        'quality',
        'weight',
        'playlist_id',
        'days_spent',
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('trips')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->trips as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('trips/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('videos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->videos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('videos/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>