common/models/Trips.php
<?php

Yii::import('common.models._base.BaseTrips');

class Trips extends BaseTrips
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}


	public function relations() {
		return array_merge(parent::relations(),array(
			'tripsCountries' => array(self::HAS_MANY, 'TripsCountries', 'trip_id'),
			'countries' => array(self::HAS_MANY, 'Countries', 'country_id', 'through' => 'tripsCountries'),
		));
	}
/* уже не актуально
	public function getMapPath() {
		// video map
		$dir = Yii::app()->basePath.'/www/trips.data/';
		$mapPath = false;
		if (is_dir($dir)) {
			if ($dh = opendir($dir)) {
				while (($file = readdir($dh)) !== false) {
					if (is_dir($dir.$file)) {
						if ((int)$file == $this->id) {
							if ($dh2 = opendir($dir.$file.'/maps/')) {
								while (($file2 = readdir($dh2)) !== false) {
									if (in_array($file2,array('.','..'))) continue;
									$mapPath = '/trips.data/'.$file.'/maps/'.$file2;
									break;
								}
								closedir($dh2);
							}
							break;
						}
					}
				}
				closedir($dh);
			}
		}
		return $mapPath;
	}
*/
}

backend/controllers/MoviesController.php
<?php

class MoviesController extends EGxController
{


    public $layout = '//layouts/column2';

    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id, 'Movies'),
        ));
    }

    public function actionCreate()
    {
        $model = new Movies;


        if (isset($_POST['Movies'])) {
            $model->setAttributes($_POST['Movies']);

            if ($model->save()) {
                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        $model = $this->loadModel($id, 'Movies');


        if (isset($_POST['Movies'])) {
            $model->setAttributes($_POST['Movies']);

            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id)
    {
        if (Yii::app()->getRequest()->getIsPostRequest()) {
            $this->loadModel($id, 'Movies')->delete();

            if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
        } else
            throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
    }

    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Movies');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionAdmin()
    {
        $model = new Movies('search');
        $model->unsetAttributes();

        if (isset($_GET['Movies']))
            $model->setAttributes($_GET['Movies']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }


    public function actionRescan123OldVersionTest()
    {

        foreach ($playlistListFeed as $playlistEntry) {


            $videoFeed = $yt->getPlaylistVideoFeed($playlistEntry->getPlaylistVideoFeedUrl());
            $i = 1;

            echo '<br/><br/><strong>' . $movie->id . ') ' . $videoFeed->getTitle() . "</strong><br/>";

            /**
             * @var Zend_Gdata_YouTube_VideoEntry $videoEntry
             */

            foreach ($videoFeed as $videoEntry) {
                $q = new CDbCriteria();
                $q->addSearchCondition('youtube_url', substr($videoEntry->getFlashPlayerUrl(), 26, 11));
                $video = Videos::model()->find($q);
                if (is_null($video)) $video = new Videos();

                echo '<br/>';
                if ($video->isNewRecord) echo ' ' . $video->sorder = $i++;
                echo ' ' . $video->name = trim(str_replace(array('Мир Приключений - ', 'Мир приключений - '), '', $videoEntry->getTitle()));
                echo ' ' . CHtml::link('ссылка', $video->youtube_url = $videoEntry->getVideoWatchPageUrl());
                echo ' ' . $video->end = $videoEntry->getVideoDuration() - 24;
                $video->movie_id = $movie->id;
                if (!$error = $video->save(false)) {
                    echo "<br/>ОШИБКА ЗАПИСИ!<br/>";
                }

            }
            //	echo $playlistEntry->title->text . "\n";
            //	echo $playlistEntry->description->text . "\n";
        }
    }


    public function actionRescan123()
    {
        Yii::import('vendor.*');

        require_once 'google/apiclient/src/Google/Client.php';
        require_once 'google/apiclient/src/Google/Service/YouTube.php';
        require_once 'google/apiclient/src/Google/Auth/AssertionCredentials.php';

        $key = file_get_contents(Yii::getPathOfAlias('application').'/../API Project-787997783c90.p12');

        $client = new Google_Client();
        $client->setApplicationName("Mir");
        $assertionCredentials = new Google_Auth_AssertionCredentials(
            '364605236788-jol0qhebs1o8keh5fbp6odthvjs3cutl@developer.gserviceaccount.com',[
            'https://www.googleapis.com/auth/youtube',
            'https://www.googleapis.com/auth/youtube.readonly'
        ], $key, 'notasecret');
        $client->setAssertionCredentials($assertionCredentials);
        $client->setClientId('364605236788-jol0qhebs1o8keh5fbp6odthvjs3cutl.apps.googleusercontent.com');

        $youtube = new Google_Service_YouTube($client);

        $playlists = $youtube->playlists->listPlaylists('id, snippet', [
            'channelId' => 'UCKMeh2DHG8TTEdvCozVUvww',
            'maxResults' => 50,
        ]);

        try {
            $v = $p = 0;
            foreach ($playlists->getItems() as $playlistItem) {
                $p++;
                $movie = Movies::model()->findByAttributes([
                    'playlist_id' => $playlistItem->getId()
                ]);
                if (!$movie) continue;

                $playlistItemsResponse = $youtube->playlistItems->listPlaylistItems('snippet', array(
                    'playlistId' => $playlistItem->getId(),
                    'maxResults' => 50
                ));
                echo '<br/><br/><strong>' . $movie->id . ') ' . $playlistItem->getSnippet()->title . "</strong><br/>";

                $i = $k = 1;
                foreach ($playlistItemsResponse->getItems() as $video) {
                    $v++;
                    $q = new CDbCriteria();
                    $q->addSearchCondition('youtube_url', $video['snippet']['resourceId']['videoId']);
                    $videoModel = Videos::model()->find($q);
                    if (is_null($videoModel)) $videoModel = new Videos();

                    echo '<br/>';
                    if ($videoModel->isNewRecord) echo '*' . $videoModel->sorder = $i++;
                    else echo ' '.$k++;
                    echo ' ' . $videoModel->name = trim(str_replace(array('Мир Приключений - ', 'Мир приключений - '), '', $video['snippet']['title']));
                    echo ' ' . CHtml::link('ссылка', $videoModel->youtube_url = sprintf('https://www.youtube.com/watch?v=%s&feature=youtube_gdata_player', $video['snippet']['resourceId']['videoId']));
                //    echo ' ' . $videoModel->end = '----';//$video->getVideoDuration() - 24;
                    $videoModel->movie_id = $movie->id;

                    if (!$error = $videoModel->save(false)) {
                        echo "<br/>ОШИБКА ЗАПИСИ!<br/>";
                    }

                }
            }
            echo '<br/>';
            echo '<hr/>';
            echo 'Total found: playlists '.$p.', videos '.$v;

        } catch (Google_Service_Exception $e) {
            echo sprintf('<p>A service error occurred: <code>%s</code></p>',
                htmlspecialchars($e->getMessage()));
        } catch (Google_Exception $e) {
            echo sprintf('<p>An client error occurred: <code>%s</code></p>',
                htmlspecialchars($e->getMessage()));
        }
    }
}

backend/controllers/PlansController.php
<?php

class PlansController extends EGxController {


    public $layout='//layouts/column2';

    public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Plans'),
		));
	}

	public function actionCreate() {
		$model = new Plans;


		if (isset($_POST['Plans'])) {
			$model->setAttributes($_POST['Plans']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Plans');


		if (isset($_POST['Plans'])) {
			$model->setAttributes($_POST['Plans']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Plans')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Plans');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Plans('search');
		$model->unsetAttributes();

		if (isset($_GET['Plans']))
			$model->setAttributes($_GET['Plans']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

backend/controllers/TripsController.php
<?php

class TripsController extends EGxController {


    public $layout='//layouts/column2';

    public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Trips'),
		));
	}

	public function actionCreate() {
		$model = new Trips;


		if (isset($_POST['Trips'])) {
			$model->setAttributes($_POST['Trips']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Trips');


		if (isset($_POST['Trips'])) {
			$model->setAttributes($_POST['Trips']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Trips')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Trips');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Trips('search');
		$model->unsetAttributes();

		if (isset($_GET['Trips']))
			$model->setAttributes($_GET['Trips']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

frontend/controllers/TripsController.php
<?php

class TripsController extends EGxController {

    public $layout='//layouts/column2';

	public function actionView($id) {

        $lang = Yii::app()->getLanguage(); $other = str_replace($lang,'','enru');
        $model = $this->loadModel($id, 'Trips',[
                'select' => "id, active, sorder, dates,
                        COALESCE(title_$lang, title_$other) as title, COALESCE(description_$lang, description_$other) as description,
                        COALESCE(scenario_$lang, scenario_$other) as scenario,
                        plan_id, movie_id"
            ]);

		$this->render('view', array(
			'model' => $model,
		));
	}

	public function actionIndex() {
        $lang = Yii::app()->getLanguage(); $other = str_replace($lang,'','enru');
        $dataProvider = new CActiveDataProvider('Trips', array(
				'pagination'=>array(
					'pageSize'=>15,
				),
				'criteria'=>array(
					'condition'=>'active=1',
					'order'=>'sorder DESC',
                    'select'=>"id, active, sorder, dates,
                        COALESCE(title_$lang, title_$other) as title, COALESCE(description_$lang, description_$other) as description,
                        plan_id, movie_id"
				),
				'countCriteria'=>array(
					'condition'=>'active=1',
				),

			)
		);
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}



	public function actionCountry($id) {
		$criteria = new CDbCriteria;

		$criteria->with = array('tripsCountries');

		$criteria->condition = 'active=1';
		$criteria->order = 'sorder DESC';

		$criteria->together = true;
		$criteria->compare('tripsCountries.country_id', $id);

		$dataProvider=new CActiveDataProvider('Trips', array(
			'criteria'=>$criteria,
			'countCriteria'=>$criteria,
			/* array(
					'condition'=>'active=1',
				 // 'order' and 'with' clauses have no meaning for the count query
				),
	*/
			'pagination'=>array(
				'pageSize'=>5,
			),
		));


		$this->render('index', array(
			'dataProvider' => $dataProvider,
			'selectedCountryId'=> $id,
		));
	}

}

backend/views/trips/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'trips-form',
	'enableAjaxValidation' => false,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'active'); ?>
		<?php echo $form->checkBox($model, 'active'); ?>
		<?php echo $form->error($model,'active'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'sorder'); ?>
		<?php echo $form->textField($model, 'sorder'); ?>
		<?php echo $form->error($model,'sorder'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model, 'title', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'title'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model, 'description'); ?>
		<?php echo $form->error($model,'description'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'youtube_map'); ?>
		<?php echo $form->textField($model, 'youtube_map', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'youtube_map'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'dates'); ?>
		<?php echo $form->textField($model, 'dates', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'dates'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'scenario'); ?>
		<?php echo $form->textArea($model, 'scenario'); ?>
		<?php echo $form->error($model,'scenario'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'plan_id'); ?>
		<?php echo $form->dropDownList($model, 'plan_id', GxHtml::listDataEx(Plans::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'plan_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'movie_id'); ?>
		<?php echo $form->dropDownList($model, 'movie_id', GxHtml::listDataEx(Movies::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'movie_id'); ?>
		</div><!-- row -->

		<label><?php echo GxHtml::encode($model->getRelationLabel('tripsCountries')); ?></label>
		<?php echo $form->checkBoxList($model, 'tripsCountries', GxHtml::encodeEx(GxHtml::listDataEx(TripsCountries::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('countries')); ?></label>
		<?php echo $form->checkBoxList($model, 'countries', GxHtml::encodeEx(GxHtml::listDataEx(Countries::model()->findAllAttributes(null, true)), false, true)); ?>

<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

backend/views/trips/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'id'); ?>
		<?php echo $form->textField($model, 'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'active'); ?>
		<?php echo $form->dropDownList($model, 'active', array('0' => Yii::t('app', 'No'), '1' => Yii::t('app', 'Yes')), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'sorder'); ?>
		<?php echo $form->textField($model, 'sorder'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'title'); ?>
		<?php echo $form->textField($model, 'title', array('maxlength' => 255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'description'); ?>
		<?php echo $form->textArea($model, 'description'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'youtube_map'); ?>
		<?php echo $form->textField($model, 'youtube_map', array('maxlength' => 255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'dates'); ?>
		<?php echo $form->textField($model, 'dates', array('maxlength' => 255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'scenario'); ?>
		<?php echo $form->textArea($model, 'scenario'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'plan_id'); ?>
		<?php echo $form->dropDownList($model, 'plan_id', GxHtml::listDataEx(Plans::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'movie_id'); ?>
		<?php echo $form->dropDownList($model, 'movie_id', GxHtml::listDataEx(Movies::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

backend/views/trips/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('active')); ?>:
	<?php echo GxHtml::encode($data->active); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('sorder')); ?>:
	<?php echo GxHtml::encode($data->sorder); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('title')); ?>:
	<?php echo GxHtml::encode($data->title); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('description')); ?>:
	<?php echo GxHtml::encode($data->description); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('youtube_map')); ?>:
	<?php echo GxHtml::encode($data->youtube_map); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('dates')); ?>:
	<?php echo GxHtml::encode($data->dates); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('scenario')); ?>:
	<?php echo GxHtml::encode($data->scenario); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('plan_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->plan)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('movie_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->movie)); ?>
	<br />
	*/ ?>

</div>

backend/views/trips/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('trips-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'trips-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'id',
		array(
					'name' => 'active',
					'value' => '($data->active === 0) ? Yii::t(\'app\', \'No\') : Yii::t(\'app\', \'Yes\')',
					'filter' => array('0' => Yii::t('app', 'No'), '1' => Yii::t('app', 'Yes')),
					),
		'sorder',
		'title',
		'description',
		'youtube_map',
		/*
		'dates',
		'scenario',
		array(
				'name'=>'plan_id',
				'value'=>'GxHtml::valueEx($data->plan)',
				'filter'=>GxHtml::listDataEx(Plans::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'movie_id',
				'value'=>'GxHtml::valueEx($data->movie)',
				'filter'=>GxHtml::listDataEx(Movies::model()->findAllAttributes(null, true)),
				),
		*/
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

backend/views/trips/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

backend/views/trips/index.php
<?php

$this->breadcrumbs = array(
	Trips::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . Trips::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . Trips::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Trips::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

backend/views/trips/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(
	array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

backend/views/trips/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
'active:boolean',
'sorder',
'title',
'description',
'youtube_map',
'dates',
'scenario',
array(
			'name' => 'plan',
			'type' => 'raw',
			'value' => $model->plan !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->plan)), array('plans/view', 'id' => GxActiveRecord::extractPkValue($model->plan, true))) : null,
			),
array(
			'name' => 'movie',
			'type' => 'raw',
			'value' => $model->movie !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->movie)), array('movies/view', 'id' => GxActiveRecord::extractPkValue($model->movie, true))) : null,
			),
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('tripsCountries')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->tripsCountries as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('tripsCountries/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('countries')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->countries as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('countries/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>